name: vga-nextgen
recipe: laravel
config:
  webroot: public
  php: 8.2
  xdebug: 'develop,debug'

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=lando"
        XDEBUG_SESSION_START: lando

  phpmyadmin:
    type: phpmyadmin

proxy:
  appserver:
    - vga-nextgen.lndo.site
    - "*.vga-nextgen.lndo.site"
